language: java

branches:
  only:
  - master

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java8-installer

after_success:
  - mvn clean test jacoco:report coveralls:jacoco

notifications:
  irc: "chat.freenode.net#gnode"
  email:
    on_failure: always